#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'api-gateway'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['api-gateway:8081']
#
#  - job_name: 'eureka-server'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:8761']
#
#  - job_name: 'newsfeed-service'
#    metrics_path: '/actuator/prometheus'
#    eureka_sd_configs:
#      - server: 'http://eureka:8761/eureka'
#    relabel_configs:
#      - source_labels: [__meta_eureka_app_name]
#        regex: 'newsfeed-service'
#        action: keep
#
#  - job_name: 'post-service'
#    metrics_path: '/actuator/prometheus'
#    eureka_sd_configs:
#      - server: 'http://eureka:8761/eureka'
#    relabel_configs:
#      - source_labels: [__meta_eureka_app_name]
#        regex: 'post-service'
#        action: keep
#
#  - job_name: 'stock-api-service'
#    metrics_path: '/actuator/prometheus'
#    eureka_sd_configs:
#      - server: 'http://eureka:8761/eureka'
#    relabel_configs:
#      - source_labels: [__meta_eureka_app_name]
#        regex: 'stock-api-service'
#        action: keep
#
#  - job_name: 'user-service'
#    metrics_path: '/actuator/prometheus'
#    eureka_sd_configs:
#      - server: 'http://eureka:8761/eureka'
#    relabel_configs:
#      - source_labels: [__meta_eureka_app_name]
#        regex: 'user-service'
#        action: keep

