services:
  redis:
    image: redis:7.2.5
    container_name: redis_newsfeed_service
    networks:
      - default
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/var/lib/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  default:
    driver: bridge


volumes:
  redis-data:
