server:
  port: 8083
spring:
  application:
    name: post-service

  datasource:
    url: jdbc:mysql://post-service-mysql:3306/post-service-mysql
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            addTypeInfo: true
    template:
      default-topic: post-event
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

springdoc:
  api-docs:
    path: /api/posts/v3/api-docs
  swagger-ui:
    path: /api/posts/swagger-ui.html

