server:
  port: 8083
spring:
  application:
    name: posting-service

  datasource:
    url: jdbc:mysql://localhost:3306/redchart_posting_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver