server:
  port: 8084
spring:
  application:
    name: auth-common
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/redchart_auth_common
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver