server:
  port: 8082
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/redchart_user_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver