services:
  redis:
    image: redis:7.2.5
    container_name: redis_user_service
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql-db:
    image: mysql:8.0.34
    container_name: mysql_user_service
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: redchart_user_service
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  default:
    driver: bridge


volumes:
  mysql-data:
  redis-data:
